import type { CourseModule } from "@/src/types/course"

export const courseModules: CourseModule[] = [
  {
    id: 0,
    slug: "physics-language",
    title: "Физический язык",
    shortDescription: "Базовые слова, обозначения и способы читать условие задачи.",
    topicCount: 8,
    progress: 100,
    status: "complete",
    icon: "🔧",
    keySkills: ["читать физические величины", "отделять данные от вопроса", "записывать краткое условие"],
    typicalMisconceptions: ["путать величину и единицу", "искать формулу до анализа условия"],
    examRelevance: "Основа для всех расчетных и качественных заданий.",
    lessons: [
      {
        slug: "physical-quantities",
        title: "Физические величины",
        shortDescription: "Что обозначают величины и как читать их в условии.",
        keySkills: ["видеть обозначения", "связывать величину с смыслом"],
        typicalMisconceptions: ["считать символ формулой сам по себе"],
        examRelevance: "Нужно для корректной записи ответа.",
      },
      {
        slug: "units-and-notation",
        title: "Единицы и обозначения",
        shortDescription: "Единицы измерения, приставки и аккуратная запись.",
        keySkills: ["распознавать единицы", "переводить приставки"],
        typicalMisconceptions: ["смешивать единицы разных систем"],
        examRelevance: "Частая причина ошибок в численных заданиях.",
      },
      {
        slug: "condition-reading",
        title: "Как читать условие",
        shortDescription: "Как выделить известное, неизвестное и лишний текст.",
        keySkills: ["делать краткую запись", "формулировать вопрос задачи"],
        typicalMisconceptions: ["переписывать текст без анализа"],
        examRelevance: "Помогает не терять баллы из-за неверной постановки задачи.",
      },
    ],
  },
  {
    id: 1,
    slug: "measurements",
    title: "Измерения",
    shortDescription: "Погрешность, шкалы приборов и перевод результатов измерений.",
    topicCount: 5,
    progress: 100,
    status: "complete",
    icon: "📏",
    keySkills: ["читать шкалу", "оценивать цену деления", "записывать результат с единицей"],
    typicalMisconceptions: ["считать цену деления по соседним подписанным числам", "забывать единицу в ответе"],
    examRelevance: "Полезно для задач с приборами, графиками и таблицами.",
    lessons: [
      {
        slug: "scale-division",
        title: "Цена деления",
        shortDescription: "Как определить малое деление на шкале.",
        keySkills: ["читать шкалы", "считать промежутки"],
        typicalMisconceptions: ["делить на количество подписей вместо промежутков"],
        examRelevance: "Встречается в заданиях с измерительными приборами.",
      },
      {
        slug: "si-conversions",
        title: "Перевод в СИ",
        shortDescription: "Как привести данные к одной системе единиц.",
        keySkills: ["переводить длину, время, массу", "проверять размерность"],
        typicalMisconceptions: ["подставлять сантиметры как метры"],
        examRelevance: "Критично для расчетных задач.",
      },
    ],
  },
  {
    id: 2,
    slug: "mechanics-motion",
    title: "Механика: движение",
    shortDescription: "Равномерное и ускоренное движение, координата, скорость и графики.",
    topicCount: 12,
    progress: 75,
    status: "active",
    icon: "🚗",
    keySkills: ["строить x(t)", "читать v(t)", "связывать скорость и перемещение"],
    typicalMisconceptions: ["путать график координаты и траекторию", "читать наклон как значение координаты"],
    examRelevance: "Один из центральных блоков механики на ЦЭ/ЦТ.",
    lessons: [
      {
        slug: "uniform-motion",
        title: "Равномерное движение",
        shortDescription: "Движение с постоянной скоростью на прямой.",
        keySkills: ["находить путь", "читать скорость"],
        typicalMisconceptions: ["считать постоянную скорость остановкой"],
        examRelevance: "База для задач на графики и движение.",
      },
      {
        slug: "accelerated-motion",
        title: "Равноускоренное движение",
        shortDescription: "Как скорость меняется со временем при постоянном ускорении.",
        keySkills: ["читать v(t)", "сравнивать ускорения", "работать с начальными условиями"],
        typicalMisconceptions: ["путать знак ускорения со знаком скорости"],
        examRelevance: "Часто проверяется через графики и краткие расчеты.",
      },
      {
        slug: "motion-graphs",
        title: "Графики движения",
        shortDescription: "Как читать координату, скорость и смысл наклона.",
        keySkills: ["читать наклон", "сопоставлять графики", "видеть участки движения"],
        typicalMisconceptions: ["принимать форму графика за форму траектории"],
        examRelevance: "Высокая значимость для тестовых и комплексных задач.",
      },
    ],
  },
  {
    id: 3,
    slug: "mechanics-forces",
    title: "Механика: силы",
    shortDescription: "Силы, равнодействующая и законы Ньютона в задачах.",
    topicCount: 10,
    progress: 30,
    status: "active",
    icon: "💪",
    keySkills: ["рисовать силы", "искать равнодействующую", "связывать силу и ускорение"],
    typicalMisconceptions: ["считать, что движение всегда требует ненулевой силы", "забывать силу реакции опоры"],
    examRelevance: "Ключевой блок для задач на динамику.",
    lessons: [
      {
        slug: "force-diagrams",
        title: "Диаграммы сил",
        shortDescription: "Как показать силы на теле без лишних стрелок.",
        keySkills: ["выделять тело", "рисовать направления сил"],
        typicalMisconceptions: ["рисовать скорость как силу"],
        examRelevance: "Помогает решать динамические задачи без угадывания.",
      },
      {
        slug: "newton-laws",
        title: "Законы Ньютона",
        shortDescription: "Связь взаимодействия, силы и изменения движения.",
        keySkills: ["применять второй закон", "понимать пары сил"],
        typicalMisconceptions: ["путать действие и противодействие на одном теле"],
        examRelevance: "Часто используется в расчетных задачах.",
      },
    ],
  },
  {
    id: 4,
    slug: "work-energy",
    title: "Работа и энергия",
    shortDescription: "Работа силы, мощность, кинетическая и потенциальная энергия.",
    topicCount: 8,
    progress: 0,
    status: "locked",
    icon: "⚡",
    keySkills: ["распознавать работу силы", "выбирать вид энергии", "сравнивать состояния"],
    typicalMisconceptions: ["смешивать работу и энергию как одно число без контекста"],
    examRelevance: "Нужно для задач на изменение состояния системы.",
    lessons: [
      {
        slug: "mechanical-work",
        title: "Механическая работа",
        shortDescription: "Когда сила совершает работу и как это записывать.",
        keySkills: ["видеть перемещение", "учитывать направление силы"],
        typicalMisconceptions: ["считать любую приложенную силу работой"],
        examRelevance: "Основа для энергетических задач.",
      },
      {
        slug: "energy-conservation",
        title: "Закон сохранения энергии",
        shortDescription: "Как сравнивать энергию в разных состояниях.",
        keySkills: ["выбирать начальное и конечное состояние", "учитывать потери"],
        typicalMisconceptions: ["забывать, что энергия меняет форму"],
        examRelevance: "Часто связывает механику с расчетами.",
      },
    ],
  },
  {
    id: 5,
    slug: "momentum",
    title: "Импульс",
    shortDescription: "Импульс тела, импульс силы и столкновения в простых моделях.",
    topicCount: 6,
    progress: 0,
    status: "locked",
    icon: "🎯",
    keySkills: ["выбирать систему тел", "сравнивать импульсы", "анализировать столкновения"],
    typicalMisconceptions: ["путать импульс тела и импульс силы"],
    examRelevance: "Полезно для задач на взаимодействие тел.",
    lessons: [
      {
        slug: "body-momentum",
        title: "Импульс тела",
        shortDescription: "Как масса и скорость задают импульс.",
        keySkills: ["учитывать направление", "работать с векторами на прямой"],
        typicalMisconceptions: ["терять знак направления"],
        examRelevance: "Подготовка к задачам на столкновения.",
      },
      {
        slug: "collisions",
        title: "Столкновения",
        shortDescription: "Как описывать взаимодействие тел до и после события.",
        keySkills: ["сравнивать состояния", "выбирать систему"],
        typicalMisconceptions: ["рассматривать только одно тело вместо системы"],
        examRelevance: "Встречается в комбинированных задачах.",
      },
    ],
  },
  {
    id: 6,
    slug: "pressure",
    title: "Давление",
    shortDescription: "Давление твердых тел, жидкостей и газов на школьном уровне.",
    topicCount: 7,
    progress: 0,
    status: "locked",
    icon: "🌊",
    keySkills: ["сравнивать давление", "читать глубину", "анализировать площадь опоры"],
    typicalMisconceptions: ["путать силу давления и давление", "забывать роль площади"],
    examRelevance: "Часто проверяется в бытовых и экспериментальных сюжетах.",
    lessons: [
      {
        slug: "solid-pressure",
        title: "Давление твердых тел",
        shortDescription: "Как сила и площадь связаны с давлением.",
        keySkills: ["сравнивать площади", "оценивать изменение давления"],
        typicalMisconceptions: ["считать большую силу всегда большим давлением"],
        examRelevance: "Типовая тема для качественных вопросов.",
      },
      {
        slug: "liquid-pressure",
        title: "Давление жидкости",
        shortDescription: "Почему глубина важна при давлении в жидкости.",
        keySkills: ["читать глубину", "сравнивать точки в жидкости"],
        typicalMisconceptions: ["ориентироваться только на форму сосуда"],
        examRelevance: "Используется в задачах на гидростатику.",
      },
    ],
  },
  {
    id: 7,
    slug: "molecular-physics",
    title: "МКТ",
    shortDescription: "Молекулярная картина вещества и простые тепловые процессы.",
    topicCount: 7,
    progress: 0,
    status: "locked",
    icon: "🔬",
    keySkills: ["связывать модель и наблюдение", "понимать агрегатные состояния", "читать тепловые графики"],
    typicalMisconceptions: ["считать молекулы неподвижными в твердом теле"],
    examRelevance: "База для тепловых явлений и газовых задач.",
    lessons: [
      {
        slug: "particle-model",
        title: "Модель частиц",
        shortDescription: "Как частицы помогают объяснять свойства вещества.",
        keySkills: ["связывать модель с явлением", "различать состояния вещества"],
        typicalMisconceptions: ["переносить макросвойства прямо на молекулы"],
        examRelevance: "Нужно для качественных вопросов.",
      },
      {
        slug: "thermal-motion",
        title: "Тепловое движение",
        shortDescription: "Что меняется при нагревании с точки зрения модели.",
        keySkills: ["объяснять нагревание", "различать температуру и тепло"],
        typicalMisconceptions: ["говорить, что температура является веществом"],
        examRelevance: "Связка между МКТ и термодинамикой.",
      },
    ],
  },
  {
    id: 8,
    slug: "thermodynamics",
    title: "Термодинамика",
    shortDescription: "Количество теплоты, теплообмен и тепловые процессы.",
    topicCount: 6,
    progress: 0,
    status: "locked",
    icon: "🔥",
    keySkills: ["читать графики нагревания", "сравнивать теплообмен", "работать с тепловыми величинами"],
    typicalMisconceptions: ["путать температуру и количество теплоты"],
    examRelevance: "Важна для задач на нагревание, плавление и теплообмен.",
    lessons: [
      {
        slug: "heat-quantity",
        title: "Количество теплоты",
        shortDescription: "Как описывать передачу энергии при нагревании.",
        keySkills: ["выбирать процесс", "сравнивать начальное и конечное состояние"],
        typicalMisconceptions: ["считать тепло запасом вещества"],
        examRelevance: "Частая расчетная тема.",
      },
      {
        slug: "phase-changes",
        title: "Фазовые переходы",
        shortDescription: "Плавление, кипение и участки без изменения температуры.",
        keySkills: ["читать график нагревания", "видеть плато процесса"],
        typicalMisconceptions: ["ожидать рост температуры во время всего нагревания"],
        examRelevance: "Встречается в графических заданиях.",
      },
    ],
  },
  {
    id: 9,
    slug: "electricity",
    title: "Электричество",
    shortDescription: "Ток, напряжение, сопротивление и простые цепи.",
    topicCount: 12,
    progress: 0,
    status: "locked",
    icon: "🔌",
    keySkills: ["читать схему цепи", "различать ток и напряжение", "сравнивать соединения"],
    typicalMisconceptions: ["думать, что ток расходуется на лампе", "путать последовательное и параллельное соединение"],
    examRelevance: "Один из крупных блоков школьной физики и экзамена.",
    lessons: [
      {
        slug: "current-voltage-resistance",
        title: "Ток, напряжение, сопротивление",
        shortDescription: "Роли основных величин в электрической цепи.",
        keySkills: ["различать величины", "читать обозначения"],
        typicalMisconceptions: ["называть напряжение силой тока"],
        examRelevance: "База для всех задач по цепям.",
      },
      {
        slug: "circuit-connections",
        title: "Соединения в цепях",
        shortDescription: "Как ведут себя величины при разных соединениях.",
        keySkills: ["видеть узлы", "сравнивать участки цепи"],
        typicalMisconceptions: ["путать ветвь и весь контур"],
        examRelevance: "Часто проверяется схемами.",
      },
    ],
  },
  {
    id: 10,
    slug: "optics",
    title: "Оптика",
    shortDescription: "Свет, отражение, преломление, линзы и изображения.",
    topicCount: 8,
    progress: 0,
    status: "locked",
    icon: "💡",
    keySkills: ["строить лучи", "читать схему линзы", "различать изображение и предмет"],
    typicalMisconceptions: ["считать, что луч существует только там, где он нарисован"],
    examRelevance: "Важна для качественных задач и построений.",
    lessons: [
      {
        slug: "reflection-refraction",
        title: "Отражение и преломление",
        shortDescription: "Как свет меняет направление на границе сред.",
        keySkills: ["читать нормаль", "сравнивать углы"],
        typicalMisconceptions: ["измерять угол от поверхности вместо нормали"],
        examRelevance: "Типовой источник ошибок в тестах.",
      },
      {
        slug: "lenses-images",
        title: "Линзы и изображения",
        shortDescription: "Как строить ход лучей в простых случаях.",
        keySkills: ["строить главные лучи", "описывать изображение"],
        typicalMisconceptions: ["путать действительное и мнимое изображение"],
        examRelevance: "Полезно для задач с построениями.",
      },
    ],
  },
  {
    id: 11,
    slug: "exam-review",
    title: "Повторение ЦЭ/ЦТ",
    shortDescription: "Системное повторение тем, типовых ошибок и экзаменационных форматов.",
    topicCount: 9,
    progress: 0,
    status: "draft",
    icon: "🏆",
    keySkills: ["выбирать стратегию решения", "проверять единицы", "разбирать ошибку после ответа"],
    typicalMisconceptions: ["повторять только формулы без задач", "не анализировать неверные ответы"],
    examRelevance: "Финальный модуль подготовки к формату ЦЭ/ЦТ.",
    lessons: [
      {
        slug: "exam-strategy",
        title: "Стратегия экзамена",
        shortDescription: "Как распределять внимание между типами заданий.",
        keySkills: ["начинать с понятного", "помечать сомнения", "проверять ответ"],
        typicalMisconceptions: ["застревать на одном задании слишком долго"],
        examRelevance: "Помогает использовать время устойчиво.",
      },
      {
        slug: "error-review",
        title: "Разбор ошибок",
        shortDescription: "Как превращать ошибку в следующий шаг обучения.",
        keySkills: ["классифицировать ошибку", "находить слабый навык"],
        typicalMisconceptions: ["считать ошибку случайностью без причины"],
        examRelevance: "Поддерживает повторение перед экзаменом.",
      },
    ],
  },
]
